name: 'Label pull request'

on:
  pull_request_review:

concurrency:
  group: '${{ github.workflow }}-${{ github.event.pull_request.number }}'

jobs:
  label:
    runs-on: ubuntu-22.04
    steps:
      - uses: myparcelnl/actions/pr-label-by-review@v5
        with:
          app-id: ${{ secrets.MYPARCEL_APP_ID }}
          private-key: ${{ secrets.MYPARCEL_APP_PRIVATE_KEY }}
          protection-type: 'rulesets'
